/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.ArrayList;
//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import locadora.controller.AtorController;
import locadora.model.Ator;

/**
 *
 * @author Aluisio
 */
public class TelaConsultaAtor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaConsultaAtor.class.getName());

    //1º) Variável de Referência
    private TelaCadastroAtor telaCadastroAtor;
    
    /**
     * Creates new form TelaConsultaAtor
     */
    public TelaConsultaAtor() {
        initComponents();
    }
    
    //2º) Método para acessar a Tela Consultar Ator.
    public TelaConsultaAtor(TelaCadastroAtor telaCadastroAtor){
        this.telaCadastroAtor = telaCadastroAtor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultaAtor = new javax.swing.JPanel();
        jLabelConsultaAtor = new javax.swing.JLabel();
        jLabelNomeAtor = new javax.swing.JLabel();
        jTextFieldNomeAtor = new javax.swing.JTextField();
        jButtonConsultaAtor = new javax.swing.JButton();
        jScrollPaneConsultaAtor = new javax.swing.JScrollPane();
        jTableConsultaAtor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filme, Pipoca e Refrigerante");
        setName("frameTelaConsultaAtor"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fecharJanela(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelConsultaAtor.setBackground(new java.awt.Color(102, 102, 102));

        jLabelConsultaAtor.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabelConsultaAtor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConsultaAtor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png"))); // NOI18N
        jLabelConsultaAtor.setText("Consulta de Ator");

        jLabelNomeAtor.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelNomeAtor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeAtor.setText("Informe o nome do ator:");

        jTextFieldNomeAtor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextFieldNomeAtor.setToolTipText("Informe o nome do ator que deseja consultar.");

        jButtonConsultaAtor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jButtonConsultaAtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAtor(evt);
            }
        });

        jTableConsultaAtor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTableConsultaAtor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Nacionalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultaAtor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaAtorMouseClicked(evt);
            }
        });
        jScrollPaneConsultaAtor.setViewportView(jTableConsultaAtor);

        javax.swing.GroupLayout jPanelConsultaAtorLayout = new javax.swing.GroupLayout(jPanelConsultaAtor);
        jPanelConsultaAtor.setLayout(jPanelConsultaAtorLayout);
        jPanelConsultaAtorLayout.setHorizontalGroup(
            jPanelConsultaAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaAtorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaAtorLayout.createSequentialGroup()
                        .addComponent(jLabelNomeAtor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeAtor, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultaAtor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneConsultaAtor))
                .addContainerGap())
            .addComponent(jLabelConsultaAtor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelConsultaAtorLayout.setVerticalGroup(
            jPanelConsultaAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaAtorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelConsultaAtor)
                .addGap(7, 7, 7)
                .addGroup(jPanelConsultaAtorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldNomeAtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultaAtor)
                    .addComponent(jLabelNomeAtor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneConsultaAtor, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelConsultaAtor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*4º) RECEBE a lista de atores buscados/pesquisados no BD pelo DAO/Classe de Conexão.
    RETORNA a Instância do Ator (MODEL) com a lista de atores para o CONTROLLER (Regras
    de Negócio): AtorController.java. Agora o botão da LUPA é programado para receber os
    dados do CONTROLLER para popular o componente TABLE no arquivo TelaConsultaAtor.java
    na camada VIEW.*/
    private void consultarAtor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAtor
        //JOptionPane.showMessageDialog(null, "Consulta o nome do ator!");
        String nome = jTextFieldNomeAtor.getText();
        DefaultTableModel tableModel = (DefaultTableModel) jTableConsultaAtor.getModel();
        tableModel.setRowCount(0);
        AtorController atorController = new AtorController();
        
        try {
            ArrayList<Ator> atores = atorController.listarAtores(nome);
            atores.forEach((Ator ator) -> {
                tableModel.addRow(new Object[] {ator.getCodAtor(),
                                                ator.getName(),
                                                ator.getNacionalidade()});
            });
            jTableConsultaAtor.setModel(tableModel);
        } catch (Exception e) {
            Logger.getLogger(TelaCadastroAtor.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_consultarAtor

    //4º) Método para fechar a janela Consulta do Ator.
    private void fecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharJanela
        this.dispose();
        this.telaCadastroAtor.setVisible(true);
    }//GEN-LAST:event_fecharJanela

    private void jTableConsultaAtorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaAtorMouseClicked
        if (evt.getClickCount() == 2) {
            Integer codAtor = (Integer) jTableConsultaAtor.getModel().getValueAt(jTableConsultaAtor.getSelectedRow(), 0);
            String nome = (String) jTableConsultaAtor.getModel().getValueAt(jTableConsultaAtor.getSelectedRow(), 1);
            String nacionalidade = (String) jTableConsultaAtor.getModel().getValueAt(jTableConsultaAtor.getSelectedRow(), 2);
            
            this.telaCadastroAtor.buscarAtor(codAtor, nome, nacionalidade);
            this.telaCadastroAtor.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTableConsultaAtorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaConsultaAtor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultaAtor;
    private javax.swing.JLabel jLabelConsultaAtor;
    private javax.swing.JLabel jLabelNomeAtor;
    private javax.swing.JPanel jPanelConsultaAtor;
    private javax.swing.JScrollPane jScrollPaneConsultaAtor;
    private javax.swing.JTable jTableConsultaAtor;
    private javax.swing.JTextField jTextFieldNomeAtor;
    // End of variables declaration//GEN-END:variables
}
