/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluisio
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin_v2
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jLabelALTF4 = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 153));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                Sair(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsuario.setBackground(new java.awt.Color(45, 43, 60));
        jTextFieldUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setToolTipText("Digite o usuário.");
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldUsuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 177, 380, 40));

        jPasswordFieldSenha.setBackground(new java.awt.Color(45, 43, 60));
        jPasswordFieldSenha.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPasswordFieldSenha.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldSenha.setToolTipText("Digite a senha.");
        jPasswordFieldSenha.setBorder(null);
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 242, 380, 40));

        jButtonLogin.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButtonLogin.setText("ENTRAR");
        jButtonLogin.setBorder(null);
        jButtonLogin.setContentAreaFilled(false);
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logar(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 308, 470, 40));

        jLabelALTF4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelALTF4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelALTF4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelALTF4.setText("ALT+F4->Fechar");
        getContentPane().add(jLabelALTF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 110, 20));

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login.png"))); // NOI18N
        getContentPane().add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Logar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logar
        if (jTextFieldUsuario.getText().equals("alu") && new String(jPasswordFieldSenha.getPassword()).equals("123")) {
            TelaPrincipal tp = new TelaPrincipal();
            tp.setVisible(true);
            limparTelaLogin(evt);
        } else{
            JOptionPane.showMessageDialog(null, "Usuário ou senha inválido!");
        }
    }//GEN-LAST:event_Logar

    private void Sair(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Sair
        System.exit(0);
    }//GEN-LAST:event_Sair

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelALTF4;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

        private void limparTelaLogin(ActionEvent evt) {
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
    }

}
