/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluisio
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName());
    
    //1º) Variável de Referência. Referencia a Tela Principal.
    private TelaPrincipal telaprincipal;
    
    //2º) Método para acessar a Tela Cadastro de Usuário.
    public TelaCadastroUsuario(TelaPrincipal telaPrincipal) {
        this.telaprincipal = telaPrincipal;
        initComponents();       
    }
    
    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonSalvar = new javax.swing.JButton();
        jLabelCadUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE USUÁRIO");
        setName("frameCadUsuario"); // NOI18N
        setPreferredSize(new java.awt.Dimension(540, 415));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                FecharCadastroUsuario(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNome.setBackground(new java.awt.Color(45, 43, 60));
        jTextFieldNome.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNome.setToolTipText("Digite o seu nome.");
        jTextFieldNome.setBorder(null);
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 350, 40));

        jTextFieldUsuario.setBackground(new java.awt.Color(45, 43, 60));
        jTextFieldUsuario.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setToolTipText("Digite o seu usuário.");
        jTextFieldUsuario.setBorder(null);
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 184, 350, 40));

        jPasswordFieldSenha.setBackground(new java.awt.Color(45, 43, 60));
        jPasswordFieldSenha.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPasswordFieldSenha.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldSenha.setToolTipText("Digite a sua senha.");
        jPasswordFieldSenha.setBorder(null);
        jPasswordFieldSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 350, 40));

        jButtonSalvar.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("");
        jButtonSalvar.setBorder(null);
        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarUsuario(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 470, 50));

        jLabelCadUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro_usuario.png"))); // NOI18N
        getContentPane().add(jLabelCadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarUsuario
        
        /*String nome = jTextFieldNome.getText();
        String usuario = jTextFieldNome.getText();
        String senha = jPasswordFieldSenha.getName().toString();
        boolean sucesso;*/
        
        JOptionPane.showMessageDialog(null, "O cadastro foi realizado com sucesso!");
        limparTelaCadastroUsuario(evt);
        
        //this.setVisible(false); CRIAREI O Método AO FECHAR O FORMULÁRIO.
        
        /*try {
            //TROCAR PARA O CÓDIGO UsuarioController, quando houver!
            
            AtorController atorController = new AtorController();
            sucesso = atorController.cadastrarAtor(nome, nacionalidade);
            
            if (sucesso == true) {
                JOptionPane.showMessageDialog(null, "O cadastro foi realizado com sucesso!");
                this.limparTelaCadastroAtor(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Os campos não foram preenchidos corretamente!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e);
        }*/
    }//GEN-LAST:event_SalvarUsuario
    
    /*3º) Método para fechar a tela de Cadastro de Usuário.
    EVENTO windowClosed do componente JFrame.*/
    private void FecharCadastroUsuario(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FecharCadastroUsuario
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);
    }//GEN-LAST:event_FecharCadastroUsuario

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCadUsuario;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    private void limparTelaCadastroUsuario(ActionEvent evt) {
        jTextFieldNome.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
    }

}
